server:
  port: 8080

spring:
  application:
    name: server
  jmx:
    enabled: true
  boot:
    admin:
      client:
        url: http://127.0.0.1:8080
        instance:
          service-url: http://127.0.0.1:8080
          name: server
      notify:
        dingtalk:
          enabled: true
          message: 1234
          webhook-url: http://127.0.0.1/
          secret:


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    env:
      show-values: always
      enabled: true
      post:
        enabled: true